export const SEARCH_FILM_ERROR = "SEARCH_FILM_ERROR";
export const GENRE_MOVIE_REQUEST = "GENRE_MOVIE_REQUEST";
export const GENRE_MOVIE_SUCCESS = "GENRE_MOVIE_SUCCESS";
export const MOVIE_BY_GENRE_REQUEST = "MOVIE_BY_GENRE_REQUEST";
export const MOVIE_BY_GENRE_SUCCESS = "MOVIE_BY_GENRE_SUCCESS";
export const MOVIE_BY_ID_REQUEST = "MOVIE_BY_ID_REQUEST";
export const MOVIE_BY_ID_SUCCESS = "MOVIE_BY_ID_SUCCESS";
