export const USER_AUTH_STATUS = "USER_AUTH_STATUS";

export const USER_LOG_IN = "USER_LOG_IN";
export const USER_LOG_OUT = "USER_LOG_OUT";

export const USER_FORM_LOGIN_ADD = "USER_FORM_LOGIN_ADD";
export const USER_FORM_FIRSTNAME_ADD = "USER_FORM_FIRSTNAME_ADD";
export const USER_FORM_LASTNAME_ADD = "USER_FORM_LASTNAME_ADD";
export const USER_FORM_EMAIL_ADD = "USER_FORM_EMAIL_ADD";
export const USER_FORM_PASSWORD_ADD = "USER_FORM_PASSWORD_ADD";
export const USER_FORM_REPASSWORD_ADD = "USER_FORM_REPASSWORD_ADD";
