version: "3"

services:
  frontend:
    container_name: HyperTube-front
    build: ./frontend
    image: hyper-tube-front
    volumes:
      - ./frontend:/app
  frontend-builder:
    container_name: HyperTube-front-build
    build:
      ./frontend/builder
    volumes:
      - /app/templates
      - /app/static
  backend:
    links:
      - frontend-builder
    container_name: HyperTube-back
    build: ./backend
    volumes:
      - ./backend:/app
      - frontend-builder
    ports:
      - 5006:5006
    restart: always