version: "3"

services:
  frontend:
    container_name: HyperTube-front
    build: ./frontend
    image: hyper-tube-front
    volumes:
      - ./frontend:/app
  frontend-builder:
    container_name: HyperTube-front-build
    build:
      ./frontend/builder
    volumes:
      - /app/static
      - ./frontend/src:/app/src
    ports:
      - 8888:8888
    restart: always
  backend:
    depends_on:
      - frontend-builder
    container_name: HyperTube-back
    build: ./backend
    volumes:
      - ./backend:/app
    volumes_from:
      - frontend-builder
    ports:
      - 5006:5006
    restart: always