version: "3"

services:
  frontend:
    container_name: HyperTube-front
    build: ./frontend
    volumes:
      - ./frontend:/app
  backend:
    depends_on:
      - frontend-builder
    container_name: HyperTube-back
    build: ./backend
    volumes:
      - ./backend:/app
      - frontend-builder
    ports:
      - 5006:5006
    restart: always
  frontend-builder:
    container_name: HyperTube-front-build
    build:
      ./frontend/builder
    volumes:
    - /app/templates
    - /app/static