export const lang = {
    ru: {
        sortBy: ['Названию', 'Год', 'Рейтинг', 'Пиры', 'Сиды', 'Кол-во скачиваний', 'Кол-во классов', 'Дата добавления'],
        sortByRuEng: {'Названию': 'title', 'Год': 'year', 'Рейтинг': 'rating', 'Пиры':'peers', 'Сиды':'seeds',
            'Кол-во скачиваний':'download_count', 'Кол-во классов':'like_count', 'Дата добавления':'date_added'},
        sortByTitle: 'Сортировать по',
        orderByTitle: 'Сортировать от',
        orderBy: ['большего к меньшему', 'меньшего к большему'],
        orderByRuEng: {'большего к меньшему': 'desc', 'меньшего к большему': 'asc'},
        rating: 'Минимальный рейтинг',
        selectGenre: 'Выбирите жанр',
        genreRuEng: {"боевик": 'Action', "приключения": 'Adventure', "мультфильм": 'Animation', "комедия": 'Comedy', "криминал": 'Crime',
            "документальный": 'Documentary', "драма": 'Drama', "семейный": 'Family', "фэнтези": 'Fantasy', "история": 'History',
            "ужасы": 'Horror', "музыка": 'Music', "детектив": 'Mystery', "мелодрама": 'Romance', "фантастика": 'Science Fiction',
            "телевизионный фильм": 'TV Movie', "триллер": 'Thriller', "военный": 'War', "вестерн": 'Western'},
        search: 'Поиск',
        user: 'Профиль',
        login: 'Имя пользователя',
        password: 'Пароль',
        logOut: 'Выйти',
        logIn: 'Войти',
        newbee: "Впервые? Зарегистрироваться",
        forget: "Забыли пароль?",
        firstName: 'Имя',
        lastName: 'Фамилия',
        email: 'Почта',
        rePassword: 'Пароль еще раз',
        remindPas: 'Напишите свою электронную почту и мы пришлем вам ссылку на восстановление',
        remindButton: 'Напомнить',
        editProfile: 'Изменить профиль',
        changeInfo: 'Изменить информацию',
        changePic: 'Изменить фото',
        changePicBut: 'Загрузить фото',
        changeLang: 'Изменить язык',
        changePas: 'Изменить пароль',
        save: 'Сохранить',
        back: 'Назад',
        signUp: 'Зарегистрироваться',
        viewed :'Просмотренно',

    },
    eng: {
        sortBy: ['title', 'year', 'rating', 'peers', 'seeds', 'download_count', 'like_count', 'date_added'],
        sortByTitle: 'Sort By',
        orderByTitle: 'Order by',
        orderBy: ['desc', 'asc'],
        rating: 'Min rating',
        selectGenre: 'Select genre',
        search: 'Search',
        user: 'User',
        logOut: 'Log out',
        newLogin: 'Your login',
        login: 'Your login',
        password: 'Your password',
        logIn: 'Sing in',
        signUp: 'Sing up',
        newbee: "Newbee? Sign up!",
        forget: "Forgot password? Remind",
        firstName: 'First name',
        lastName: 'Last name',
        email: 'Email',
        rePassword: 'Re-Password',
        remindPas: 'Enter your email address to receive a secured link',
        remindButton: 'Remind',
        editProfile: 'Edit profile',
        changeInfo: 'Change information',
        changePic: 'Change photo',
        changeLang: 'Change language',
        changePicBut: 'Upload new image',
        changePas: 'Change password',
        save: 'Save',
        back: 'Back',
        viewed: 'viewed'
    },

}